# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: PowerShell@2
  displayName: 'Install .NET 4.6.1 Targeting Pack'
  inputs:
    targetType: 'inline'
    script: |
      $url = "https://go.microsoft.com/fwlink/?linkid=2099470"
      $installer = "$env:TEMP\NDP461-DevPack.exe"
      Invoke-WebRequest -Uri $url -OutFile $installer
      Start-Process -FilePath $installer -Args "/quiet /norestart" -Wait
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:TargetFrameworkVersion=v4.6.1'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  enabled: false
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**\*.csproj;!**\*.Test.csproj'
    versioningScheme: 'off'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'